### ISSUE TITLE
/boot/clear.txt doesn't remove all images

### ISSUE THREAD

**Issue by Chetic** [PiInTheSky/pits#10]
As the software seems to look to me, not all .jpg-files are stored in ~/pits/tracker/images.
From tracker.c:

```
    if (FileExists("/boot/clear.txt"))
    ...
        system("rm -rf /home/pi/pits/tracker/images/*.jpg");
```

**Comment by PiInTheSky** [comment]
Yes, all the images are in that folder tree,
