### ISSUE TITLE
malloc() function in aprs.c

### ISSUE THREAD

**Issue by rlharris** [PiInTheSky/pits#11]
I was browsing through the source code for aprs.c (refreshing my very stale C knowledge). I saw that malloc() is used to dynamically allocate memory in makeafsk() but I cannot find where the allocated memory is ever released using free().

Perhaps for most balloon flights there is no danger of exhausting the available RAM but as a matter of good housekeeping shouldn't one free the memory back to the pool?

Or did I miss something?

**Comment by PiInTheSky** [comment]
Cheers.  Yes that was a (small) leak - 44 bytes every 1 minute.  Not enough to cause a problem but needed fixing, and has been.
