### ISSUE TITLE
Barometric Altitude.

### ISSUE THREAD

**Issue by ED6E0F17** [PiInTheSky/pits#14]
Atmospheric pressure is more accurate than GPS for calculating Ascent Rate at low altitudes. This should give a more stable/accurate landing prediction on the live tracker.

It would be interesting to compare GPS altitude at burst with the equivalent Ardupilot method:

https://github.com/diydrones/ardupilot/blob/master/libraries/AP_Baro/AP_Baro.cpp#L200

**Comment by PiInTheSky** [comment]
Ardupilot's atmospheric model is inaccurate above 2km.  Readily available pressure sensors are not useful at 30km or above.  I have no intention of using barometric data to calculate the altitude.

**Comment by fab4space** [comment]
I hope you don't want to break an altitude record :p
