### ISSUE TITLE
BME280 readings zero

### ISSUE THREAD

**Issue by Ryan-Ing** [PiInTheSky/pits#18]
I have set BME280=Y, and now I have the correct amount of fields but readings of zero. I have the VCC pin to 3Vo, SDA to SDI, SCL to SCK, Ground to ground. i2c is enabled. Do you know why this is?

**Comment by daveake** [comment]
It should be enable_bme280=Y

**Comment by Ryan-Ing** [comment]
It is set to that

**Comment by daveake** [comment]
OK, not what you said.

Your BME280 isn't being seen on the i2c bus.  You can check what 
addresses are active using the i2cdetect program (find instructions for 
installation and use on the web).

The BME280 can be set to address ox76 or 0x77.  The software checks 
both.  With zero results, the device is not present on either, which 
means it's dead or not wired correctly.

**Comment by Ryan-Ing** [comment]
The following addresses are active. Im pretty sure I have wired it correctly, is there any reason why it might be dead.

![fullsizerender](https://cloud.githubusercontent.com/assets/19475894/17209549/65d7bc32-54b5-11e6-946e-72e9c3c01135.jpg)

**Comment by daveake** [comment]
Run the tracker program from the command line and see what it sees on 
startup.

**Comment by Ryan-Ing** [comment]
It keeps showing "error writing to i2c slave" and it says the bme280 sensor is found at address 76h

**Comment by daveake** [comment]
Do you have the option of setting yours to 76h ?

**Comment by Ryan-Ing** [comment]
Im sorry, I know nothing about coding. So no, I dont think so

**Comment by daveake** [comment]
No, I mean the device itself.  Does it have a jumper setting or similar to
change address?  This is a feature of the BME280.

**Comment by Ryan-Ing** [comment]
Yes, I can add a jumper from SDO to GND, but it still says "error writing to i2c slave"

**Comment by daveake** [comment]
Run i2detect with the jumper in each position and tell me what that says.

**Comment by Ryan-Ing** [comment]
With the jumper SDO to GND: 
![76](https://cloud.githubusercontent.com/assets/19475894/17272918/8c2dab16-569b-11e6-843d-e04ba4b7392a.jpg)

With it wired normally:

![77](https://cloud.githubusercontent.com/assets/19475894/17272922/9a55d330-569b-11e6-9214-3799041d09e4.jpg)

**Comment by daveake** [comment]
Set to one address, close/restart the tracker program, see if it works.

If not, set to other address, close/restart the tracker program, see if it
works.

If it doesn't work in either setting then it's faulty.

The software autodetects which address it's on, and so should work with
either address.  I've only tested with one address as my BME280 board
doesn't have the option to change.  I don't recall which address mine uses
but it does work.

**Comment by Ryan-Ing** [comment]
Aha! It's working now on the 76 address. Thank you very much for your help, I appreciate it!
