### ISSUE TITLE
process_image needs to be executable but that is not documented ?

### ISSUE THREAD

**Issue by zanco** [PiInTheSky/pits#22]
Hi, last week I tried to get my on screen text back on the SSDV image. Everything I tried but no SSDV images where transmitted.  After renaming process_image the SSDV TX started again.

Convert gave an error so I tried to change the owner from root to pi with no luck.

However, chmod +x solved the error and now all works great again.

Regards,
Ben

**Comment by PiInTheSky** [comment]
Have added to new readme.md file.
