### ISSUE TITLE
convert in pits tracker gives error messages

### ISSUE THREAD

**Issue by zanco** [PiInTheSky/pits#24]
Hi, the images from my jpeg camera give errors:

`Resolution: 1280x720
Components: 3
DQT table for component 1: 00, Sampling factor: 2x2
DQT table for component 2: 01, Sampling factor: 1x1
DQT table for component 3: 01, Sampling factor: 1x1
MCU blocks: 3600
Components: 3
Component 1 DHT: 00
Component 2 DHT: 11
Component 3 DHT: 11
convert: Corrupt JPEG data: 101 extraneous bytes before marker 0xd9 `/home/pi/pits/tracker/images/LORA1/15_21_30.jpg' @ warning/jpeg.c/JPEGWarningHandler/352.
convert: unable to read font `Dosis-Medium' @ warning/annotate.c/RenderType/872.
convert: unable to read font `Dosis-Medium' @ warning/annotate.c/RenderType/872.
convert: Corrupt JPEG data: 101 extraneous bytes before marker 0xd9 `/home/pi/pits/tracker/images/LORA1/15_21_30.jpg' @ warning/jpeg.c/JPEGWarningHandler/352.
convert: unable to read font `Dosis-Medium' @ warning/annotate.c/RenderType/872.
convert: unable to read font `Dosis-Medium' @ warning/annotate.c/RenderType/872.
convert: Corrupt JPEG data: 101 extraneous bytes before marker 0xd9 `/home/pi/pits/tracker/images/LORA1/15_21_30.jpg' @ warning/jpeg.c/JPEGWarningHandler/352.
convert: unable to read font `Dosis-Medium' @ warning/annotate.c/RenderType/872.
convert: unable to read font `Dosis-Medium' @ warning/annotate.c/RenderType/872.
convert: unable to read font `Dosis-Medium' @ warning/annotate.c/RenderType/872.
convert: unable to read font `Dosis-Medium' @ warning/annotate.c/RenderType/872.
convert: Corrupt JPEG data: 101 extraneous bytes before marker 0xd9 `/home/pi/pits/tracker/images/LORA1/15_21_30.jpg' @ warning/jpeg.c/JPEGWarningHandler/352.
convert: unable to read font `Dosis-Medium' @ warning/annotate.c/RenderType/872.
convert: unable to read font `Dosis-Medium' @ warning/annotate.c/RenderType/872.
convert: unable to read font `Dosis-Medium' @ warning/annotate.c/RenderType/872.
convert: unable to read font `Dosis-Medium' @ warning/annotate.c/RenderType/872.
convert: Corrupt JPEG data: 101 extraneous bytes before marker 0xd9 `/home/pi/pits/tracker/images/LORA1/15_21_30.jpg' @ warning/jpeg.c/JPEGWarningHandler/352.
convert: unable to read font `Dosis-Medium' @ warning/annotate.c/RenderType/872.
convert: unable to read font `Dosis-Medium' @ warning/annotate.c/RenderType/872.
convert: unable to read font `Dosis-Medium' @ warning/annotate.c/RenderType/872.
convert: unable to read font `Dosis-Medium' @ warning/annotate.c/RenderType/872.
Precision: 8
`

resolution is 1280 8 720 and nothing has changed on the camera side. The images get transmitted although I notice a lot of garbaged images.

Anything I should change or edit in my settings ?

Thanks,

**Comment by PiInTheSky** [comment]
" unable to read font" indicates that you haven't installed that particular font; you can get it from https://www.fontsquirrel.com/fonts/dosis

I have no idea why your camera is producing bad jpeg data.
