### ISSUE TITLE
Feature: Send command to Tracker to switch wifi on

### ISSUE THREAD

**Issue by xpix** [PiInTheSky/pits#26]
Hello, if it possible to send some commands to the tracker to trigger an action. I.e. here in germany it's possible that our payload is landed on the highest tree in the forest. A good solution on the RPI Zero W is to switch on an WIFI AP to get all the video and telemetry data. To save power, it will be very nice that i can send a command to the tracker that he switch his WIFI AP on, i can connect this via my phone and can download all relevant data.

If this possible and how can i implement this?

thx Frank

**Comment by daveake** [comment]
I'm working on a generic upload facility which I hope to release later this
summer, and that will include the ability to run an external command, so
that would do what you need.

**Comment by xpix** [comment]
Thanks for the fast answer! Wait on this Feature :)

**Comment by daveake** [comment]
OK, it took 3 years, but uploads are now implemented as promised!
