### ISSUE TITLE
Raspbian Stretch and Pits not starting at boot

### ISSUE THREAD

**Issue by NA9VY** [PiInTheSky/pits#28]
Good evening,
Have there been any issues reported with Raspbian Stretch and Pits not starting at boot. I can log in and start everything (I think) by entering ./startup in the tracker directory.

I'm going to try and find a copy of Raspbian Jessie to do the installation with but that will have to wait for another day.
Thanks,
Chris

**Comment by daveake** [comment]
Yes, had such a report yesterday.  Will investigate soon.

**Comment by daveake** [comment]
Moved auto start over to systemd.

**Comment by NA9VY** [comment]
Thanks, David! I'll try it out tomorrow or this week.
Chris
