### ISSUE TITLE
Landing prediction

### ISSUE THREAD

**Issue by labjg** [PiInTheSky/pits#30]
I recall there was an option in /boot/pisky.txt to enable landing prediction, a few versions ago.  I assume this was related to the post at [http://www.daveakerman.com/?p=2059](url), which is clearly a work in progress, but I do wonder whether this is in the current PITS release?

The pisky.txt option has since disappeared, but I do see prediction.c and prediction.txt sitting in the pits/tracker directory.

Possible to turn this on?

**Comment by daveake** [comment]
It's still possible:

landing_prediction=Y
cd_area=0.5
payload_weight=1.0

Replace the numbers with real ones if you have them, to improve the prediction prior to burst, but the software calculates the parachute effectiveness automatically during descent.

The calculated position,landing speed and time are then included in the telemetry.
