### ISSUE TITLE
Feature: LoRa REG_PA_DAC 20dBm

### ISSUE THREAD

**Issue by plowell** [PiInTheSky/pits#33]
Modify Lora.c to allow use of 20dBm for those loud Americans cluttering up the spectrum.

Perhaps something like:
// 20dBm
**#define REG_PA_DAC	0x4D
#define PA_DAC_20	0x87**

// transmit section of lora.c
case RF98_MODE_TX:
writeRegister(LoRaChannel, REG_LNA, LNA_OFF_GAIN);     // TURN LNA OFF FOR TRANSMITT
writeRegister(LoRaChannel, REG_PA_CONFIG, Config.LoRaDevices[LoRaChannel].Power);
**if (Config.LoRaDevices[LoRaChannel].Power == 0xFF) {      // Turn on additional amp for 20dBm
     writeRegister(LoRaChannel, REG_PA_DAC, PA_DAC_20);
     }**

I recently flew this and it made a huge difference.   http://www.ncnearspace.org/missions/nsl-67

**Comment by daveake** [comment]
Added to latest version out this week.
