### ISSUE TITLE
default installation user

### ISSUE THREAD

**Issue by kafka399** [PiInTheSky/pits#35]
Hi,

If you build the software under different username than "pi", then tracker won't start as the %path% to the software is hardcoded.

    sudo vi /lib/systemd/system/tracker.service

And replace the username.

**Comment by kafka399** [comment]
Additionally, path is hardcoded in startup script

**Comment by daveake** [comment]
Correct.  We expect customers to follow the supplied instructions which
install the software under the pi user.  For the intended use it is simpler
for the code, installation, manual and associated articles to assume
installation for the pi user, so we won't be charging it.
