### ISSUE TITLE
PITS internal temperature not updating on pi zero

### ISSUE THREAD

**Issue by MGPZ** [PiInTheSky/pits#38]
Hi

When using the PITS tracker on a Pi Zero (without the PITSZero board, just GPS and LoRa modules attached) the internal temperature reading is not updating so the initial reading taken from the GPU just repeats for the duration it is running. 

If I restart the tracker, an updated temperature reading is reported but again this repeats without updating.

Many Thanks

Mark

**Comment by PiInTheSky** [comment]
Thanks, sounds like it's only checking once or is re-reading the same data
for some reason.  I'll check over the weekend.

**Comment by MGPZ** [comment]
Happy to help.

Mark

**Comment by PiInTheSky** [comment]
Fixed in latest issue.

It was setting a flag that said it had found a DS18B20, and that stopped further checks of the GPU temperature.
