### ISSUE TITLE
Power Save - silence rather than null packets

### ISSUE THREAD

**Issue by KevWal** [PiInTheSky/pits#41]
Hi

As discussed, it would be good to have an option to send silence rather than Null packets in order to do some power saving.

Thanks very much, Kevin

**Comment by PiInTheSky** [comment]
Will do/

**Comment by daveake** [comment]
You can use TDM mode which does this - e.g. send once every 15 seconds.  Is that enough?

**Comment by KevWal** [comment]
Not sure what I was looking for here now, suggest we close this ;)
