### ISSUE TITLE
Time via GPS

### ISSUE THREAD

**Issue by jrobinson-uk** [PiInTheSky/pits#8]
Can we update the system time via the GPS data ?

**Comment by daveake** [comment]
It does it already :-)

**Comment by jrobinson-uk** [comment]
okay, thought you said it was in the pipeline, nevermind

**Comment by daveake** [comment]
Yeah, it was added to the LoRa branch fairly recently, and now of course 
is in the main branch.

Dave

**Comment by PiInTheSky** [comment]
Code is in gps.c.  It sets the system time once a GPRMC sentence has been received with a valid time.
